
stuba_ldap: &STUBA_LDAP
  host: ldap.stuba.sk
  port: 636
  attribute: uid
  base: ou=People,dc=stuba,dc=sk
  ssl: simple_tls

## Environment
development:
  <<: *STUBA_LDAP # Use the VPN, Luke. Or local users.

test:
  <<: *STUBA_LDAP

staging:
  <<: *STUBA_LDAP

production:
  <<: *STUBA_LDAP
