# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2751348c0c26e995a96c60a5f4c007633b0a1c50e48d99a0a61aa33cbb68ac2a0a8a4b144c2cdcd0d74e0bd3e67963958c0c3d3b2508d050a9ef0a7cfe017c6

test:
  secret_key_base: 7e98f2a49942c3212c9eb965e882f19b63085f89017f58ae7c481e805983c9a1793d820a35c79cf20f47b1837974ff10803ede4fad62bf2dcfe0ba6ef9198da0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["ALEFTNG_SECRET_KEY_BASE"] %>

staging:
  secret_key_base: <%= ENV["ALEFTNG_SECRET_KEY_BASE"] %>

sandbox:
  secret_key_base: <%= ENV["ALEFTNG_SECRET_KEY_BASE"] %>
